# Generated by Django 3.2.10 on 2022-02-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True)),
                ('material', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('numero_solicitud', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
    ]
