# Generated by Django 3.2.10 on 2022-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestModelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_solicitud',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='modelo_solicitud',
            name='numero_solicitud',
            field=models.CharField(max_length=50, verbose_name='Número de solicitud'),
        ),
        migrations.AlterField(
            model_name='modelo_solicitud',
            name='unidad_medida',
            field=models.CharField(max_length=100, verbose_name='Unidad de medida'),
        ),
    ]
