# Generated by Django 3.2.10 on 2022-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('grupo', models.CharField(max_length=100)),
                ('solapin', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, choices=[('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], default=None, max_length=50, verbose_name='Categoría')),
                ('material', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
