# Generated by Django 3.2.10 on 2022-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestMateriales', '0002_alter_material_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Profesor', 'Profesor'), ('Estudiante', 'Estudiante')], default=None, max_length=50, verbose_name='Categoría'),
        ),
    ]
